#!/bin/bash

echo "======================================"
echo "WERKSTATT.DE - IMPLEMENTATION VERIFICATION"
echo "======================================"
echo ""

echo "✓ Checking GitHub Actions Workflow..."
test -f .github/workflows/import-osm-data.yml && echo "  ✓ import-osm-data.yml exists" || echo "  ✗ Missing!"

echo ""
echo "✓ Checking API Files..."
test -f routes/api.php && echo "  ✓ routes/api.php exists" || echo "  ✗ Missing!"
test -f app/Http/Controllers/Api/PostController.php && echo "  ✓ PostController.php exists" || echo "  ✗ Missing!"
test -f app/Http/Resources/PostResource.php && echo "  ✓ PostResource.php exists" || echo "  ✗ Missing!"

echo ""
echo "✓ Checking Webhook System..."
test -f config/webhooks.php && echo "  ✓ webhooks.php config exists" || echo "  ✗ Missing!"
test -f app/Services/WebhookService.php && echo "  ✓ WebhookService.php exists" || echo "  ✗ Missing!"
test -f app/Events/PostPublished.php && echo "  ✓ PostPublished.php exists" || echo "  ✗ Missing!"
test -f app/Listeners/SendPostToWebhooks.php && echo "  ✓ SendPostToWebhooks.php exists" || echo "  ✗ Missing!"

echo ""
echo "✓ Checking SEO Tools..."
test -f app/Console/Commands/GenerateSitemap.php && echo "  ✓ GenerateSitemap.php exists" || echo "  ✗ Missing!"
test -f app/Http/Middleware/SetSeoDefaults.php && echo "  ✓ SetSeoDefaults.php exists" || echo "  ✗ Missing!"
test -f resources/views/components/schema-markup.blade.php && echo "  ✓ schema-markup.blade.php exists" || echo "  ✗ Missing!"
test -f public/robots.txt && echo "  ✓ robots.txt exists" || echo "  ✗ Missing!"

echo ""
echo "✓ Checking Documentation..."
test -f FINAL_FEATURES_COMPLETE.md && echo "  ✓ FINAL_FEATURES_COMPLETE.md exists" || echo "  ✗ Missing!"

echo ""
echo "======================================"
echo "VERIFICATION COMPLETE"
echo "======================================"
echo ""
echo "Next Steps:"
echo "1. Configure webhook URLs in .env"
echo "2. Run: php artisan sitemap:generate"
echo "3. Setup queue worker for webhooks"
echo "4. Setup cron for scheduler"
echo ""
